# Site
title:              Hugo's Blog.
bio:                'A blog for sharing my experiments on data science, machine learning and cool science stuff.'
description:        "This is my blog."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/home/saturn.jpg'
background:         'assets/img/home/background.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://hgpadovani.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   hgpadovani

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              hgpadovani@gmail.com
#twitter:            username
#facebook:           hugo.padovani
github-url:         hgpadovani
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           hugo-alexandre-padovani-guimarães-de-camargo-9a3b0a56
#xing:              username
instagram:          hgpadovani
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              hgpadovani
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
